#!/bin/bash

sudo setenforce 0
sudo su; sudo livecd-creator --fslabel=Majapahit-Linux-dev-x86_64-29 --config=majapahit-dev.ks --verbose --cache=junk-dont-push/cache --tmpdir=junk-dont-push/temp
sudo chown leader:leader *.iso
sudo setenforce 1
