#!/bin/bash

sudo setenforce 0
sudo livecd-creator \
    --fslabel=Majapahit-Linux-std-x86_64-29.1 \
    --config=majapahit-std.ks \
    --cache=majapahit-cache \
    --tmpdir=majapahit-temp \
    --verbose
sudo chown kaostronomi:kaostronomi *.iso
sudo setenforce 1
